// Registro delle icone selezionabili per categorie e conti.
// Import espliciti: solo queste icone finiscono nel bundle.
import {
  Activity,
  Apple,
  Armchair,
  ArrowDownToLine,
  ArrowRightLeft,
  ArrowUpFromLine,
  Baby,
  Backpack,
  BadgeEuro,
  Banknote,
  Bath,
  BedDouble,
  Beef,
  Beer,
  Bike,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  CakeSlice,
  Calculator,
  CalendarCheck,
  Camera,
  Car,
  CarTaxiFront,
  Caravan,
  Carrot,
  Cat,
  ChartLine,
  ChartPie,
  Circle,
  Clapperboard,
  ClipboardList,
  Cloud,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Croissant,
  Dices,
  Dog,
  Drama,
  Droplet,
  Droplets,
  Dumbbell,
  Egg,
  Ellipsis,
  Euro,
  FileText,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Guitar,
  Hammer,
  HandCoins,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  House,
  IceCreamCone,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Map,
  MapPin,
  Milk,
  Monitor,
  Moon,
  Motorbike,
  Mountain,
  Music,
  Music2,
  Navigation,
  NotebookPen,
  Package,
  PaintRoller,
  Palette,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneTakeoff,
  Plug,
  Podcast,
  Popcorn,
  Printer,
  Puzzle,
  Radio,
  Receipt,
  ReceiptEuro,
  Refrigerator,
  Repeat,
  Route,
  Router,
  Salad,
  Sandwich,
  School,
  Scissors,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  Sparkles,
  SprayCan,
  SquareParking,
  Stamp,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Tag,
  Tent,
  Thermometer,
  Ticket,
  TrainFront,
  TramFront,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  Undo2,
  UserRound,
  Users,
  Utensils,
  Vault,
  Volleyball,
  Wallet,
  WashingMachine,
  Wifi,
  WifiHigh,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  'wallet': Wallet,
  'banknote': Banknote,
  'coins': Coins,
  'piggy-bank': PiggyBank,
  'badge-euro': BadgeEuro,
  'euro': Euro,
  'credit-card': CreditCard,
  'landmark': Landmark,
  'receipt': Receipt,
  'receipt-euro': ReceiptEuro,
  'hand-coins': HandCoins,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'percent': Percent,
  'calculator': Calculator,
  'vault': Vault,
  'gem': Gem,
  'briefcase-business': BriefcaseBusiness,
  'house': House,
  'key-round': KeyRound,
  'building-2': Building2,
  'sofa': Sofa,
  'lamp': Lamp,
  'bed-double': BedDouble,
  'bath': Bath,
  'zap': Zap,
  'flame': Flame,
  'droplet': Droplet,
  'wifi': Wifi,
  'wrench': Wrench,
  'hammer': Hammer,
  'paint-roller': PaintRoller,
  'plug': Plug,
  'thermometer': Thermometer,
  'trash-2': Trash2,
  'washing-machine': WashingMachine,
  'refrigerator': Refrigerator,
  'armchair': Armchair,
  'shopping-cart': ShoppingCart,
  'shopping-basket': ShoppingBasket,
  'apple': Apple,
  'carrot': Carrot,
  'beef': Beef,
  'fish': Fish,
  'croissant': Croissant,
  'milk': Milk,
  'egg': Egg,
  'spray-can': SprayCan,
  'utensils': Utensils,
  'coffee': Coffee,
  'wine': Wine,
  'beer': Beer,
  'pizza': Pizza,
  'sandwich': Sandwich,
  'cake-slice': CakeSlice,
  'ice-cream-cone': IceCreamCone,
  'cookie': Cookie,
  'salad': Salad,
  'car': Car,
  'fuel': Fuel,
  'car-taxi-front': CarTaxiFront,
  'bus': Bus,
  'train-front': TrainFront,
  'tram-front': TramFront,
  'bike': Bike,
  'plane': Plane,
  'ship': Ship,
  'route': Route,
  'square-parking': SquareParking,
  'shield-check': ShieldCheck,
  'stamp': Stamp,
  'droplets': Droplets,
  'map-pin': MapPin,
  'navigation': Navigation,
  'caravan': Caravan,
  'motorbike': Motorbike,
  'repeat': Repeat,
  'tv': Tv,
  'music': Music,
  'smartphone': Smartphone,
  'cloud': Cloud,
  'laptop': Laptop,
  'monitor': Monitor,
  'headphones': Headphones,
  'gamepad-2': Gamepad2,
  'wifi-high': WifiHigh,
  'router': Router,
  'printer': Printer,
  'camera': Camera,
  'radio': Radio,
  'podcast': Podcast,
  'clapperboard': Clapperboard,
  'heart-pulse': HeartPulse,
  'pill': Pill,
  'stethoscope': Stethoscope,
  'smile': Smile,
  'syringe': Syringe,
  'activity': Activity,
  'dumbbell': Dumbbell,
  'footprints': Footprints,
  'flask-conical': FlaskConical,
  'scissors': Scissors,
  'sparkles': Sparkles,
  'sun': Sun,
  'moon': Moon,
  'ticket': Ticket,
  'palette': Palette,
  'book-open': BookOpen,
  'popcorn': Popcorn,
  'drama': Drama,
  'party-popper': PartyPopper,
  'music-2': Music2,
  'guitar': Guitar,
  'volleyball': Volleyball,
  'trophy': Trophy,
  'dices': Dices,
  'puzzle': Puzzle,
  'tent': Tent,
  'mountain': Mountain,
  'map': Map,
  'plane-takeoff': PlaneTakeoff,
  'user-round': UserRound,
  'users': Users,
  'baby': Baby,
  'paw-print': PawPrint,
  'dog': Dog,
  'cat': Cat,
  'gift': Gift,
  'heart': Heart,
  'graduation-cap': GraduationCap,
  'notebook-pen': NotebookPen,
  'school': School,
  'backpack': Backpack,
  'briefcase': Briefcase,
  'tag': Tag,
  'undo-2': Undo2,
  'calendar-check': CalendarCheck,
  'file-text': FileText,
  'building': Building,
  'handshake': Handshake,
  'clipboard-list': ClipboardList,
  'shopping-bag': ShoppingBag,
  'shirt': Shirt,
  'arrow-right-left': ArrowRightLeft,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-up-from-line': ArrowUpFromLine,
  'ellipsis': Ellipsis,
  'circle': Circle,
  'star': Star,
  'flag': Flag,
  'bookmark': Bookmark,
  'package': Package,
  'box': Box,
  'leaf': Leaf,
}

export const ICON_GROUPS: { label: string; icons: string[] }[] = [
  { label: 'Denaro', icons: ['wallet', 'banknote', 'coins', 'piggy-bank', 'badge-euro', 'euro', 'credit-card', 'landmark', 'receipt', 'receipt-euro', 'hand-coins', 'trending-up', 'trending-down', 'chart-line', 'chart-pie', 'percent', 'calculator', 'vault', 'gem', 'briefcase-business'] },
  { label: 'Casa', icons: ['house', 'key-round', 'building-2', 'sofa', 'lamp', 'bed-double', 'bath', 'zap', 'flame', 'droplet', 'wifi', 'wrench', 'hammer', 'paint-roller', 'plug', 'thermometer', 'trash-2', 'washing-machine', 'refrigerator', 'armchair'] },
  { label: 'Spesa e cibo', icons: ['shopping-cart', 'shopping-basket', 'apple', 'carrot', 'beef', 'fish', 'croissant', 'milk', 'egg', 'spray-can', 'utensils', 'coffee', 'wine', 'beer', 'pizza', 'sandwich', 'cake-slice', 'ice-cream-cone', 'cookie', 'salad'] },
  { label: 'Trasporti', icons: ['car', 'fuel', 'car-taxi-front', 'bus', 'train-front', 'tram-front', 'bike', 'plane', 'ship', 'route', 'square-parking', 'shield-check', 'stamp', 'droplets', 'map-pin', 'navigation', 'caravan', 'motorbike'] },
  { label: 'Abbonamenti e tech', icons: ['repeat', 'tv', 'music', 'smartphone', 'cloud', 'laptop', 'monitor', 'headphones', 'gamepad-2', 'wifi-high', 'router', 'printer', 'camera', 'radio', 'podcast', 'clapperboard'] },
  { label: 'Salute e sport', icons: ['heart-pulse', 'pill', 'stethoscope', 'smile', 'syringe', 'activity', 'dumbbell', 'footprints', 'flask-conical', 'scissors', 'sparkles', 'sun', 'moon'] },
  { label: 'Svago', icons: ['ticket', 'palette', 'book-open', 'popcorn', 'drama', 'party-popper', 'music-2', 'guitar', 'volleyball', 'trophy', 'dices', 'puzzle', 'tent', 'mountain', 'map', 'plane-takeoff'] },
  { label: 'Persone e famiglia', icons: ['user-round', 'users', 'baby', 'paw-print', 'dog', 'cat', 'gift', 'heart', 'graduation-cap', 'notebook-pen', 'school', 'backpack'] },
  { label: 'Lavoro', icons: ['briefcase', 'tag', 'undo-2', 'calendar-check', 'file-text', 'building', 'handshake', 'clipboard-list'] },
  { label: 'Altro', icons: ['shopping-bag', 'shirt', 'arrow-right-left', 'arrow-down-to-line', 'arrow-up-from-line', 'ellipsis', 'circle', 'star', 'flag', 'bookmark', 'package', 'box', 'leaf'] },
]

export function getIcon(name: string | null | undefined): LucideIcon {
  return (name && ICONS[name]) || Circle
}
