import type { Muscle } from './muscles'

export type ExerciseCategory = 'gym' | 'crossfit' | 'corpo libero'

/**
 * Come si misura un esercizio:
 * - reps: carico (kg, opzionale) × ripetizioni
 * - time: durata in secondi (es. plank)
 * - distance: metri percorsi, con carico opzionale (es. farmer walk)
 * - cardio: durata in minuti + distanza in km (macchine cardio, camminata)
 */
export type Measure = 'reps' | 'time' | 'distance' | 'cardio'

export type Exercise = {
  key: string
  name: string
  primary: Muscle[]
  secondary: Muscle[]
  equipment: string
  category: ExerciseCategory
  measure: Measure
  custom?: boolean
}

// Esercizi che non si misurano a ripetizioni.
const MEASURES: Record<string, Measure> = {
  plank: 'time',
  'plank-laterale': 'time',
  'hollow-hold': 'time',
  'l-sit': 'time',
  'wall-sit': 'time',
  'mountain-climber': 'time',
  'battle-rope': 'time',
  'saltelli-con-la-corda': 'time',
  'dead-hang-sospensione-alla-sbarra': 'time',
  'farmer-walk': 'distance',
  'sled-push': 'distance',
  'handstand-walk': 'distance',
  'shuttle-run': 'distance',
  'vogatore-row': 'cardio',
  'assault-bike': 'cardio',
  cyclette: 'cardio',
  'tapis-roulant': 'cardio',
  ellittica: 'cardio',
  skierg: 'cardio',
  'stair-climber': 'cardio',
  camminata: 'cardio',
  'camminata-in-salita-tapis-roulant': 'cardio',
}

const e = (key: string, name: string, primary: Muscle[], secondary: Muscle[], equipment: string, category: ExerciseCategory): Exercise => ({
  key,
  name,
  primary,
  secondary,
  equipment,
  category,
  measure: MEASURES[key] ?? 'reps',
})

/** Catalogo base: palestra, CrossFit e corpo libero con muscoli primari e secondari. */
export const CATALOG: Exercise[] = [
  e('panca-piana-con-bilanciere', 'Panca piana con bilanciere', ['chest'], ['triceps', 'front_delts'], 'Bilanciere', 'gym'),
  e('panca-piana-con-manubri', 'Panca piana con manubri', ['chest'], ['triceps', 'front_delts'], 'Manubri', 'gym'),
  e('panca-inclinata-con-bilanciere', 'Panca inclinata con bilanciere', ['chest'], ['front_delts', 'triceps'], 'Bilanciere', 'gym'),
  e('panca-inclinata-con-manubri', 'Panca inclinata con manubri', ['chest'], ['front_delts', 'triceps'], 'Manubri', 'gym'),
  e('panca-declinata-con-bilanciere', 'Panca declinata con bilanciere', ['chest'], ['triceps'], 'Bilanciere', 'gym'),
  e('panca-declinata-con-manubri', 'Panca declinata con manubri', ['chest'], ['triceps'], 'Manubri', 'gym'),
  e('chest-press', 'Chest press', ['chest'], ['triceps', 'front_delts'], 'Macchina', 'gym'),
  e('chest-press-inclinata', 'Chest press inclinata', ['chest'], ['front_delts', 'triceps'], 'Macchina', 'gym'),
  e('croci-con-manubri', 'Croci con manubri', ['chest'], ['front_delts'], 'Manubri', 'gym'),
  e('croci-su-panca-inclinata', 'Croci su panca inclinata', ['chest'], ['front_delts'], 'Manubri', 'gym'),
  e('croci-ai-cavi', 'Croci ai cavi', ['chest'], ['front_delts'], 'Cavi', 'gym'),
  e('croci-ai-cavi-dal-basso', 'Croci ai cavi dal basso', ['chest'], ['front_delts'], 'Cavi', 'gym'),
  e('pec-deck', 'Pec deck', ['chest'], ['front_delts'], 'Macchina', 'gym'),
  e('pullover-con-manubrio', 'Pullover con manubrio', ['chest'], ['lats', 'triceps'], 'Manubri', 'gym'),
  e('piegamenti-push-up', 'Piegamenti (push-up)', ['chest'], ['triceps', 'front_delts', 'abs'], 'Corpo libero', 'corpo libero'),
  e('piegamenti-inclinati', 'Piegamenti inclinati', ['chest'], ['triceps', 'front_delts'], 'Corpo libero', 'corpo libero'),
  e('piegamenti-declinati', 'Piegamenti declinati', ['chest'], ['front_delts', 'triceps'], 'Corpo libero', 'corpo libero'),
  e('dip-alle-parallele-petto', 'Dip alle parallele (petto)', ['chest'], ['triceps', 'front_delts'], 'Parallele', 'corpo libero'),
  e('panca-piana-al-multipower', 'Panca piana al multipower', ['chest'], ['triceps', 'front_delts'], 'Smith', 'gym'),
  e('floor-press', 'Floor press', ['chest'], ['triceps'], 'Bilanciere', 'gym'),
  e('svend-press', 'Svend press', ['chest'], ['front_delts'], 'Disco', 'gym'),
  e('trazioni-alla-sbarra-pull-up', 'Trazioni alla sbarra (pull-up)', ['lats'], ['biceps', 'upper_back', 'forearms'], 'Sbarra', 'corpo libero'),
  e('trazioni-presa-supina-chin-up', 'Trazioni presa supina (chin-up)', ['lats'], ['biceps', 'upper_back'], 'Sbarra', 'corpo libero'),
  e('trazioni-presa-neutra', 'Trazioni presa neutra', ['lats'], ['biceps', 'upper_back'], 'Sbarra', 'corpo libero'),
  e('trazioni-assistite', 'Trazioni assistite', ['lats'], ['biceps', 'upper_back'], 'Macchina', 'gym'),
  e('lat-machine-avanti', 'Lat machine avanti', ['lats'], ['biceps', 'upper_back'], 'Cavi', 'gym'),
  e('lat-machine-presa-stretta', 'Lat machine presa stretta', ['lats'], ['biceps', 'upper_back'], 'Cavi', 'gym'),
  e('lat-machine-presa-inversa', 'Lat machine presa inversa', ['lats'], ['biceps'], 'Cavi', 'gym'),
  e('pulley-basso', 'Pulley basso', ['upper_back'], ['lats', 'biceps', 'rear_delts'], 'Cavi', 'gym'),
  e('rematore-con-bilanciere', 'Rematore con bilanciere', ['upper_back'], ['lats', 'biceps', 'rear_delts', 'lower_back'], 'Bilanciere', 'gym'),
  e('rematore-con-manubrio', 'Rematore con manubrio', ['lats'], ['upper_back', 'biceps', 'rear_delts'], 'Manubri', 'gym'),
  e('rematore-su-panca-inclinata', 'Rematore su panca inclinata', ['upper_back'], ['lats', 'rear_delts', 'biceps'], 'Manubri', 'gym'),
  e('pendlay-row', 'Pendlay row', ['upper_back'], ['lats', 'biceps', 'lower_back'], 'Bilanciere', 'gym'),
  e('t-bar-row', 'T-bar row', ['upper_back'], ['lats', 'biceps', 'rear_delts'], 'Bilanciere', 'gym'),
  e('low-row-alla-macchina', 'Low row alla macchina', ['upper_back'], ['lats', 'biceps'], 'Macchina', 'gym'),
  e('pulldown-a-braccia-tese', 'Pulldown a braccia tese', ['lats'], ['triceps'], 'Cavi', 'gym'),
  e('rematore-inverso-inverted-row', 'Rematore inverso (inverted row)', ['upper_back'], ['lats', 'biceps', 'rear_delts'], 'Corpo libero', 'corpo libero'),
  e('stacco-da-terra', 'Stacco da terra', ['lower_back'], ['glutes', 'hamstrings', 'quads', 'traps', 'forearms'], 'Bilanciere', 'gym'),
  e('stacco-rumeno', 'Stacco rumeno', ['hamstrings'], ['glutes', 'lower_back'], 'Bilanciere', 'gym'),
  e('stacco-rumeno-con-manubri', 'Stacco rumeno con manubri', ['hamstrings'], ['glutes', 'lower_back'], 'Manubri', 'gym'),
  e('stacco-sumo', 'Stacco sumo', ['glutes'], ['quads', 'hamstrings', 'adductors', 'lower_back'], 'Bilanciere', 'gym'),
  e('good-morning', 'Good morning', ['hamstrings'], ['lower_back', 'glutes'], 'Bilanciere', 'gym'),
  e('hyperextension', 'Hyperextension', ['lower_back'], ['glutes', 'hamstrings'], 'Panca', 'gym'),
  e('superman', 'Superman', ['lower_back'], ['glutes'], 'Corpo libero', 'corpo libero'),
  e('scrollate-con-bilanciere', 'Scrollate con bilanciere', ['traps'], ['forearms'], 'Bilanciere', 'gym'),
  e('scrollate-con-manubri', 'Scrollate con manubri', ['traps'], ['forearms'], 'Manubri', 'gym'),
  e('rack-pull', 'Rack pull', ['lower_back'], ['traps', 'glutes', 'hamstrings'], 'Bilanciere', 'gym'),
  e('seal-row', 'Seal row', ['upper_back'], ['lats', 'rear_delts'], 'Bilanciere', 'gym'),
  e('military-press', 'Military press', ['front_delts'], ['side_delts', 'triceps', 'traps'], 'Bilanciere', 'gym'),
  e('lento-avanti-con-manubri', 'Lento avanti con manubri', ['front_delts'], ['side_delts', 'triceps'], 'Manubri', 'gym'),
  e('shoulder-press-alla-macchina', 'Shoulder press alla macchina', ['front_delts'], ['side_delts', 'triceps'], 'Macchina', 'gym'),
  e('arnold-press', 'Arnold press', ['front_delts'], ['side_delts', 'triceps'], 'Manubri', 'gym'),
  e('push-press', 'Push press', ['front_delts'], ['side_delts', 'triceps', 'quads', 'glutes'], 'Bilanciere', 'crossfit'),
  e('alzate-laterali', 'Alzate laterali', ['side_delts'], ['traps'], 'Manubri', 'gym'),
  e('alzate-laterali-ai-cavi', 'Alzate laterali ai cavi', ['side_delts'], ['traps'], 'Cavi', 'gym'),
  e('alzate-laterali-alla-macchina', 'Alzate laterali alla macchina', ['side_delts'], [], 'Macchina', 'gym'),
  e('alzate-frontali', 'Alzate frontali', ['front_delts'], ['side_delts'], 'Manubri', 'gym'),
  e('alzate-frontali-con-disco', 'Alzate frontali con disco', ['front_delts'], ['side_delts'], 'Disco', 'gym'),
  e('alzate-posteriori-reverse-fly', 'Alzate posteriori (reverse fly)', ['rear_delts'], ['upper_back'], 'Manubri', 'gym'),
  e('reverse-pec-deck', 'Reverse pec deck', ['rear_delts'], ['upper_back'], 'Macchina', 'gym'),
  e('face-pull', 'Face pull', ['rear_delts'], ['upper_back', 'traps'], 'Cavi', 'gym'),
  e('tirate-al-mento', 'Tirate al mento', ['side_delts'], ['traps', 'biceps'], 'Bilanciere', 'gym'),
  e('pike-push-up', 'Pike push-up', ['front_delts'], ['triceps', 'side_delts'], 'Corpo libero', 'corpo libero'),
  e('handstand-push-up', 'Handstand push-up', ['front_delts'], ['triceps', 'side_delts', 'traps'], 'Corpo libero', 'crossfit'),
  e('y-raise', 'Y-raise', ['side_delts'], ['traps', 'rear_delts'], 'Manubri', 'gym'),
  e('curl-con-bilanciere', 'Curl con bilanciere', ['biceps'], ['forearms'], 'Bilanciere', 'gym'),
  e('curl-con-bilanciere-ez', 'Curl con bilanciere EZ', ['biceps'], ['forearms'], 'Bilanciere EZ', 'gym'),
  e('curl-con-manubri', 'Curl con manubri', ['biceps'], ['forearms'], 'Manubri', 'gym'),
  e('curl-a-martello', 'Curl a martello', ['biceps'], ['forearms'], 'Manubri', 'gym'),
  e('curl-su-panca-inclinata', 'Curl su panca inclinata', ['biceps'], [], 'Manubri', 'gym'),
  e('curl-concentrato', 'Curl concentrato', ['biceps'], [], 'Manubri', 'gym'),
  e('curl-alla-panca-scott', 'Curl alla panca Scott', ['biceps'], ['forearms'], 'Bilanciere EZ', 'gym'),
  e('curl-ai-cavi', 'Curl ai cavi', ['biceps'], ['forearms'], 'Cavi', 'gym'),
  e('curl-alla-macchina', 'Curl alla macchina', ['biceps'], [], 'Macchina', 'gym'),
  e('curl-a-martello-ai-cavi-corda', 'Curl a martello ai cavi (corda)', ['biceps'], ['forearms'], 'Cavi', 'gym'),
  e('spider-curl', 'Spider curl', ['biceps'], [], 'Manubri', 'gym'),
  e('curl-inverso', 'Curl inverso', ['forearms'], ['biceps'], 'Bilanciere', 'gym'),
  e('curl-dei-polsi', 'Curl dei polsi', ['forearms'], [], 'Manubri', 'gym'),
  e('farmer-walk', 'Farmer walk', ['forearms'], ['traps', 'abs', 'glutes'], 'Manubri', 'crossfit'),
  e('push-down-ai-cavi', 'Push down ai cavi', ['triceps'], [], 'Cavi', 'gym'),
  e('push-down-con-corda', 'Push down con corda', ['triceps'], [], 'Cavi', 'gym'),
  e('french-press-con-bilanciere-ez', 'French press con bilanciere EZ', ['triceps'], [], 'Bilanciere EZ', 'gym'),
  e('estensioni-sopra-la-testa-con-manubrio', 'Estensioni sopra la testa con manubrio', ['triceps'], [], 'Manubri', 'gym'),
  e('estensioni-sopra-la-testa-ai-cavi', 'Estensioni sopra la testa ai cavi', ['triceps'], [], 'Cavi', 'gym'),
  e('kickback-con-manubrio', 'Kickback con manubrio', ['triceps'], [], 'Manubri', 'gym'),
  e('panca-presa-stretta', 'Panca presa stretta', ['triceps'], ['chest', 'front_delts'], 'Bilanciere', 'gym'),
  e('dip-alle-parallele-tricipiti', 'Dip alle parallele (tricipiti)', ['triceps'], ['chest', 'front_delts'], 'Parallele', 'corpo libero'),
  e('dip-su-panca', 'Dip su panca', ['triceps'], ['front_delts'], 'Panca', 'corpo libero'),
  e('piegamenti-presa-stretta-diamond', 'Piegamenti presa stretta (diamond)', ['triceps'], ['chest', 'front_delts'], 'Corpo libero', 'corpo libero'),
  e('dip-alla-macchina', 'Dip alla macchina', ['triceps'], ['chest'], 'Macchina', 'gym'),
  e('squat-con-bilanciere', 'Squat con bilanciere', ['quads'], ['glutes', 'hamstrings', 'adductors', 'lower_back', 'abs'], 'Bilanciere', 'gym'),
  e('front-squat', 'Front squat', ['quads'], ['glutes', 'abs', 'upper_back'], 'Bilanciere', 'gym'),
  e('squat-al-multipower', 'Squat al multipower', ['quads'], ['glutes', 'hamstrings'], 'Smith', 'gym'),
  e('goblet-squat', 'Goblet squat', ['quads'], ['glutes', 'abs'], 'Kettlebell', 'gym'),
  e('squat-a-corpo-libero-air-squat', 'Squat a corpo libero (air squat)', ['quads'], ['glutes', 'hamstrings'], 'Corpo libero', 'corpo libero'),
  e('box-squat', 'Box squat', ['quads'], ['glutes', 'hamstrings'], 'Bilanciere', 'gym'),
  e('hack-squat', 'Hack squat', ['quads'], ['glutes'], 'Macchina', 'gym'),
  e('pressa-45', 'Pressa 45°', ['quads'], ['glutes', 'hamstrings', 'adductors'], 'Macchina', 'gym'),
  e('leg-extension', 'Leg extension', ['quads'], [], 'Macchina', 'gym'),
  e('affondi-con-manubri', 'Affondi con manubri', ['quads'], ['glutes', 'hamstrings', 'adductors'], 'Manubri', 'gym'),
  e('affondi-camminati', 'Affondi camminati', ['quads'], ['glutes', 'hamstrings'], 'Manubri', 'gym'),
  e('affondi-inversi', 'Affondi inversi', ['glutes'], ['quads', 'hamstrings'], 'Manubri', 'gym'),
  e('affondi-laterali', 'Affondi laterali', ['adductors'], ['quads', 'glutes'], 'Manubri', 'gym'),
  e('bulgarian-split-squat', 'Bulgarian split squat', ['quads'], ['glutes', 'hamstrings', 'adductors'], 'Manubri', 'gym'),
  e('step-up-sulla-panca', 'Step-up sulla panca', ['quads'], ['glutes', 'hamstrings'], 'Manubri', 'gym'),
  e('sissy-squat', 'Sissy squat', ['quads'], [], 'Corpo libero', 'corpo libero'),
  e('pistol-squat', 'Pistol squat', ['quads'], ['glutes', 'abs'], 'Corpo libero', 'crossfit'),
  e('wall-sit', 'Wall sit', ['quads'], ['glutes'], 'Corpo libero', 'corpo libero'),
  e('overhead-squat', 'Overhead squat', ['quads'], ['glutes', 'front_delts', 'abs', 'upper_back'], 'Bilanciere', 'crossfit'),
  e('hip-thrust-con-bilanciere', 'Hip thrust con bilanciere', ['glutes'], ['hamstrings', 'quads'], 'Bilanciere', 'gym'),
  e('hip-thrust-alla-macchina', 'Hip thrust alla macchina', ['glutes'], ['hamstrings'], 'Macchina', 'gym'),
  e('ponte-glutei-glute-bridge', 'Ponte glutei (glute bridge)', ['glutes'], ['hamstrings'], 'Corpo libero', 'corpo libero'),
  e('glute-kickback-ai-cavi', 'Glute kickback ai cavi', ['glutes'], ['hamstrings'], 'Cavi', 'gym'),
  e('abductor-machine', 'Abductor machine', ['abductors'], ['glutes'], 'Macchina', 'gym'),
  e('adductor-machine', 'Adductor machine', ['adductors'], [], 'Macchina', 'gym'),
  e('camminata-laterale-con-elastico', 'Camminata laterale con elastico', ['abductors'], ['glutes'], 'Elastico', 'corpo libero'),
  e('frog-pump', 'Frog pump', ['glutes'], [], 'Corpo libero', 'corpo libero'),
  e('leg-curl-sdraiato', 'Leg curl sdraiato', ['hamstrings'], ['calves'], 'Macchina', 'gym'),
  e('leg-curl-seduto', 'Leg curl seduto', ['hamstrings'], [], 'Macchina', 'gym'),
  e('leg-curl-in-piedi', 'Leg curl in piedi', ['hamstrings'], [], 'Macchina', 'gym'),
  e('nordic-curl', 'Nordic curl', ['hamstrings'], ['glutes'], 'Corpo libero', 'corpo libero'),
  e('stacco-a-gambe-tese', 'Stacco a gambe tese', ['hamstrings'], ['lower_back', 'glutes'], 'Bilanciere', 'gym'),
  e('stacco-a-una-gamba', 'Stacco a una gamba', ['hamstrings'], ['glutes', 'lower_back'], 'Manubri', 'gym'),
  e('kettlebell-swing', 'Kettlebell swing', ['glutes'], ['hamstrings', 'lower_back', 'front_delts', 'abs'], 'Kettlebell', 'crossfit'),
  e('calf-raise-in-piedi', 'Calf raise in piedi', ['calves'], [], 'Macchina', 'gym'),
  e('calf-raise-seduto', 'Calf raise seduto', ['calves'], [], 'Macchina', 'gym'),
  e('calf-raise-alla-pressa', 'Calf raise alla pressa', ['calves'], [], 'Macchina', 'gym'),
  e('calf-raise-con-manubri', 'Calf raise con manubri', ['calves'], [], 'Manubri', 'gym'),
  e('calf-raise-a-una-gamba', 'Calf raise a una gamba', ['calves'], [], 'Corpo libero', 'corpo libero'),
  e('calf-raise-al-multipower', 'Calf raise al multipower', ['calves'], [], 'Smith', 'gym'),
  e('saltelli-con-la-corda', 'Saltelli con la corda', ['calves'], ['cardio'], 'Corda', 'crossfit'),
  e('crunch', 'Crunch', ['abs'], [], 'Corpo libero', 'corpo libero'),
  e('crunch-inverso', 'Crunch inverso', ['abs'], [], 'Corpo libero', 'corpo libero'),
  e('crunch-ai-cavi', 'Crunch ai cavi', ['abs'], ['obliques'], 'Cavi', 'gym'),
  e('crunch-alla-macchina', 'Crunch alla macchina', ['abs'], [], 'Macchina', 'gym'),
  e('plank', 'Plank', ['abs'], ['obliques', 'lower_back'], 'Corpo libero', 'corpo libero'),
  e('plank-laterale', 'Plank laterale', ['obliques'], ['abs'], 'Corpo libero', 'corpo libero'),
  e('sollevamento-gambe-alla-sbarra', 'Sollevamento gambe alla sbarra', ['abs'], ['obliques'], 'Sbarra', 'corpo libero'),
  e('sollevamento-gambe-a-terra', 'Sollevamento gambe a terra', ['abs'], [], 'Corpo libero', 'corpo libero'),
  e('toes-to-bar', 'Toes to bar', ['abs'], ['lats', 'obliques', 'forearms'], 'Sbarra', 'crossfit'),
  e('knees-to-elbow', 'Knees to elbow', ['abs'], ['lats', 'obliques'], 'Sbarra', 'crossfit'),
  e('russian-twist', 'Russian twist', ['obliques'], ['abs'], 'Disco', 'corpo libero'),
  e('bicycle-crunch', 'Bicycle crunch', ['obliques'], ['abs'], 'Corpo libero', 'corpo libero'),
  e('ab-wheel-ruota', 'Ab wheel (ruota)', ['abs'], ['lats', 'lower_back'], 'Ruota', 'gym'),
  e('dead-bug', 'Dead bug', ['abs'], [], 'Corpo libero', 'corpo libero'),
  e('hollow-hold', 'Hollow hold', ['abs'], [], 'Corpo libero', 'crossfit'),
  e('v-up', 'V-up', ['abs'], [], 'Corpo libero', 'corpo libero'),
  e('sit-up', 'Sit-up', ['abs'], [], 'Corpo libero', 'crossfit'),
  e('ghd-sit-up', 'GHD sit-up', ['abs'], ['quads'], 'GHD', 'crossfit'),
  e('pallof-press', 'Pallof press', ['obliques'], ['abs'], 'Cavi', 'gym'),
  e('woodchopper-ai-cavi', 'Woodchopper ai cavi', ['obliques'], ['abs', 'front_delts'], 'Cavi', 'gym'),
  e('mountain-climber', 'Mountain climber', ['abs'], ['quads', 'front_delts', 'cardio'], 'Corpo libero', 'corpo libero'),
  e('l-sit', 'L-sit', ['abs'], ['triceps', 'quads'], 'Parallele', 'crossfit'),
  e('clean-girata', 'Clean (girata)', ['quads'], ['glutes', 'hamstrings', 'traps', 'lower_back'], 'Bilanciere', 'crossfit'),
  e('power-clean', 'Power clean', ['quads'], ['glutes', 'hamstrings', 'traps', 'lower_back'], 'Bilanciere', 'crossfit'),
  e('hang-power-clean', 'Hang power clean', ['traps'], ['quads', 'glutes', 'hamstrings'], 'Bilanciere', 'crossfit'),
  e('clean-and-jerk', 'Clean and jerk', ['quads'], ['glutes', 'front_delts', 'triceps', 'traps'], 'Bilanciere', 'crossfit'),
  e('snatch-strappo', 'Snatch (strappo)', ['quads'], ['glutes', 'hamstrings', 'traps', 'front_delts'], 'Bilanciere', 'crossfit'),
  e('power-snatch', 'Power snatch', ['quads'], ['glutes', 'traps', 'front_delts'], 'Bilanciere', 'crossfit'),
  e('thruster', 'Thruster', ['quads'], ['glutes', 'front_delts', 'triceps'], 'Bilanciere', 'crossfit'),
  e('thruster-con-manubri', 'Thruster con manubri', ['quads'], ['glutes', 'front_delts', 'triceps'], 'Manubri', 'crossfit'),
  e('wall-ball', 'Wall ball', ['quads'], ['glutes', 'front_delts', 'cardio'], 'Palla medica', 'crossfit'),
  e('burpee', 'Burpee', ['cardio'], ['chest', 'quads', 'triceps', 'abs'], 'Corpo libero', 'crossfit'),
  e('burpee-over-the-bar', 'Burpee over the bar', ['cardio'], ['chest', 'quads', 'abs'], 'Corpo libero', 'crossfit'),
  e('box-jump', 'Box jump', ['quads'], ['glutes', 'calves', 'cardio'], 'Box', 'crossfit'),
  e('box-step-over', 'Box step-over', ['quads'], ['glutes', 'cardio'], 'Box', 'crossfit'),
  e('muscle-up-alla-sbarra', 'Muscle-up alla sbarra', ['lats'], ['triceps', 'chest', 'abs'], 'Sbarra', 'crossfit'),
  e('muscle-up-agli-anelli', 'Muscle-up agli anelli', ['lats'], ['triceps', 'chest', 'abs'], 'Anelli', 'crossfit'),
  e('ring-dip', 'Ring dip', ['triceps'], ['chest', 'front_delts'], 'Anelli', 'crossfit'),
  e('ring-row', 'Ring row', ['upper_back'], ['lats', 'biceps'], 'Anelli', 'crossfit'),
  e('kipping-pull-up', 'Kipping pull-up', ['lats'], ['biceps', 'abs'], 'Sbarra', 'crossfit'),
  e('chest-to-bar', 'Chest to bar', ['lats'], ['biceps', 'upper_back'], 'Sbarra', 'crossfit'),
  e('rope-climb-salita-alla-fune', 'Rope climb (salita alla fune)', ['lats'], ['biceps', 'forearms', 'abs'], 'Fune', 'crossfit'),
  e('double-under', 'Double under', ['calves'], ['cardio', 'forearms'], 'Corda', 'crossfit'),
  e('devil-press', 'Devil press', ['cardio'], ['chest', 'glutes', 'front_delts', 'hamstrings'], 'Manubri', 'crossfit'),
  e('dumbbell-snatch', 'Dumbbell snatch', ['glutes'], ['front_delts', 'traps', 'hamstrings'], 'Manubri', 'crossfit'),
  e('kettlebell-clean', 'Kettlebell clean', ['glutes'], ['traps', 'forearms'], 'Kettlebell', 'crossfit'),
  e('turkish-get-up', 'Turkish get-up', ['abs'], ['front_delts', 'glutes', 'obliques'], 'Kettlebell', 'crossfit'),
  e('sandbag-clean', 'Sandbag clean', ['glutes'], ['lower_back', 'traps', 'biceps'], 'Sandbag', 'crossfit'),
  e('sled-push', 'Sled push', ['quads'], ['glutes', 'calves', 'cardio'], 'Slitta', 'crossfit'),
  e('handstand-walk', 'Handstand walk', ['front_delts'], ['triceps', 'abs'], 'Corpo libero', 'crossfit'),
  e('wall-walk', 'Wall walk', ['front_delts'], ['triceps', 'abs'], 'Corpo libero', 'crossfit'),
  e('battle-rope', 'Battle rope', ['front_delts'], ['abs', 'cardio', 'forearms'], 'Corde', 'crossfit'),
  e('shuttle-run', 'Shuttle run', ['cardio'], ['quads', 'calves'], 'Corpo libero', 'crossfit'),
  e('vogatore-row', 'Vogatore (row)', ['cardio'], ['lats', 'upper_back', 'quads', 'glutes'], 'Vogatore', 'crossfit'),
  e('assault-bike', 'Assault bike', ['cardio'], ['quads', 'front_delts'], 'Bike', 'crossfit'),
  e('cyclette', 'Cyclette', ['cardio'], ['quads', 'calves'], 'Bike', 'gym'),
  e('tapis-roulant', 'Tapis roulant', ['cardio'], ['quads', 'calves', 'hamstrings'], 'Tapis roulant', 'gym'),
  e('ellittica', 'Ellittica', ['cardio'], ['quads', 'glutes'], 'Ellittica', 'gym'),
  e('skierg', 'SkiErg', ['cardio'], ['lats', 'triceps', 'abs'], 'SkiErg', 'crossfit'),
  e('camminata', 'Camminata', ['cardio'], ['calves', 'glutes'], 'Corpo libero', 'corpo libero'),
  e('camminata-in-salita-tapis-roulant', 'Camminata in salita (tapis roulant)', ['cardio'], ['glutes', 'calves', 'hamstrings'], 'Tapis roulant', 'gym'),
  e('dead-hang-sospensione-alla-sbarra', 'Dead hang (sospensione alla sbarra)', ['forearms'], ['lats', 'upper_back'], 'Sbarra', 'corpo libero'),
  e('stair-climber', 'Stair climber', ['cardio'], ['glutes', 'quads', 'calves'], 'Macchina', 'gym'),
]
